-- to refer to the tables there are the queries for each 
SELECT * 
FROM sql_challenges.customers;

SELECT * 
FROM sql_challenges.orders;

SELECT * 
FROM sql_challenges.baskets;

SELECT * 
FROM sql_challenges.products;

SELECT * 
FROM sql_challenges.country;

-- 1. What are the names of all the countries in the country table?
SELECT country_name
FROM sql_challenges.country;

-- 2. What is the total number of customers in the customers table? 
SELECT COUNT(customer_id) AS no_of_customers
FROM sql_challenges.customers;

-- 3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?
SELECT AVG(age) AS avg_age
FROM sql_challenges.customers
WHERE can_email = "yes"; 

-- 4. How many orders were made by customers aged 30 or older? 
SELECT COUNT(order_id) AS no_of_orders
FROM customers 
	INNER JOIN orders
	ON customers.customer_id = orders.customer_id
WHERE age >= 30;

-- 5. What is the total revenue generated by each product category?
SELECT category, SUM(price) AS total_revenue
FROM products
	INNER JOIN baskets
	ON products.product_id = baskets.product_id
GROUP BY category
ORDER BY total_revenue DESC; 

-- 6. What is the average price of products in the 'food' category?
SELECT category, AVG(price) AS avg_price
FROM products
WHERE category = "food";

-- 7. How many orders were made in each sales channel (sales_channel column) in the orders table?
SELECT sales_channel, COUNT(order_id) AS no_of_orders
FROM orders
GROUP BY sales_channel;

-- 8.What is the date of the latest order made by a customer who can receive marketing emails?
SELECT date_shop, customers.customer_id
FROM customers
	INNER JOIN orders
    	ON customers.customer_id = orders.customer_id
WHERE can_email = "yes"
ORDER BY date_shop DESC
LIMIT 1; 

-- 9. What is the name of the country with the highest number of orders?
SELECT country_name, COUNT(order_id) AS no_of_orders
FROM orders
    INNER JOIN country
    ON orders.country_id = country.country_id
GROUP BY country_name
ORDER BY no_of_orders DESC
LIMIT 1; 

-- 10. What is the average age of customers who made orders in the 'vitamins' product category?
SELECT AVG(age)
FROM products
    INNER JOIN baskets
    ON products.product_id = baskets.product_id
    INNER JOIN orders
    ON baskets.order_id = orders.order_id
    INNER JOIN customers
    ON orders.customer_id = customers.customer_id
WHERE category = "vitamins";
