-- to refer to each table on its own these are the statements 
SELECT *
FROM sql_challenges.cars;

SELECT *
FROM sql_challenges.sales;

SELECT *
FROM salespersons;

-- joining all the tables using inner join
-- name the table created after joining the tables using the CREATE VIEW statement (named the new joined table car_showroom)
CREATE VIEW car_showroom AS
SELECT 
    salespersons.salesman_id, 
    name, 
    age, 
    city, 
    sale_id, 
    sales.car_id, 
    purchase_date, 
    make, 
    type, 
    style, 
    cost_$
FROM salespersons
	INNER JOIN sales
    	ON salespersons.salesman_id = sales.salesman_id
    	INNER JOIN cars
   	ON sales.car_id = cars.car_id;

-- you can always come back to this statement when you want to refer to the details of the joined table 
SELECT *
FROM car_showroom
ORDER BY sale_id;

-- 1. What are the details of all cars purchased in the year 2022?
SELECT
    purchase_date, 
    make, 
    type, 
    style, 
    car_showroom.car_id, 
    car_showroom.salesman_id, 
    sale_id, 
    name AS salesman_name, 
    age AS salesman_age, 
    city, 
    cost_$
FROM car_showroom
WHERE YEAR(purchase_date) = 2022
ORDER BY cost_$ DESC;

-- total revenue generated in the year 2022 (just an addition)
SELECT SUM(cost_$) AS total_car_sales
FROM car_showroom
WHERE YEAR(purchase_date) = 2022;

-- 2. What is the total number of cars sold by each salesperson?
SELECT DISTINCT(name) AS salesperson_name, COUNT(make) AS no_of_sales
FROM car_showroom
GROUP BY salesperson_name
ORDER BY no_of_sales DESC;

-- 3. What is the total revenue generated by each salesperson?
SELECT DISTINCT(name) AS salesperson_name, salesman_id, SUM(cost_$) AS total_revenue
FROM car_showroom
GROUP BY salesperson_name, salesman_id
ORDER BY total_revenue DESC;

-- 4. What are the details of the cars sold by each salesperson?
SELECT 	
    salesman_id, 
    name, 
    city, 
    car_id, 
    CONCAT(make, " ", type, " ", style) AS car_model, 
    cost_$
FROM car_showroom
GROUP BY 
    salesman_id, 
    name, 
    city, 
    car_id, 
    cost_$
ORDER BY salesman_id;

-- OR YOU CAN DISPLAY ECH OF THE SALESPERSONS LIKE THIS 
-- a. cars sold by John Smith
SELECT name, city, car_id, CONCAT(make, " ", type, " ", style) AS car_model, cost_$
FROM car_showroom
WHERE name = "John Smith" 
ORDER BY cost_$ DESC;

-- b. cars sold by Emily Wong 
SELECT name, city, car_id, CONCAT(make, " ", type, " ", style) AS car_model, cost_$
FROM car_showroom
WHERE name = "Emily Wong" 
ORDER BY cost_$ DESC;

-- c. cars sold by Tom Lee
SELECT name, city, car_id, CONCAT(make, " ", type, " ", style) AS car_model, cost_$
FROM car_showroom
WHERE name = "Tom Lee" 
ORDER BY cost_$ DESC;

-- d. cars sold by Lucy Chen
SELECT name, city, car_id, CONCAT(make, " ", type, " ", style) AS car_model, cost_$
FROM car_showroom
WHERE name = "Lucy Chen" 
ORDER BY cost_$ DESC;  

-- 5. What is the total revenue generated by each car type?
SELECT type, SUM(cost_$) AS total_revenue
FROM car_showroom
GROUP BY type
ORDER BY total_revenue DESC;

-- 6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
SELECT 
    car_id, 
    YEAR(purchase_date),  
    make, 
    type, 
    style, 
    cost_$
FROM car_showroom
WHERE YEAR(purchase_date) = 2021 AND name = "Emily Wong"; 

-- 7. What is the total revenue generated by the sales of hatchback cars?
SELECT DISTINCT(style), SUM(cost_$) AS total_revenue
FROM car_showroom
WHERE style = "Hatchback";

-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?
SELECT style, SUM(cost_$) AS total_revenue2022
FROM car_showroom
WHERE YEAR(purchase_date) = 2022 AND style = "SUV"
GROUP BY style;

-- 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
SELECT name, city, COUNT(make) AS no_ofsales_2023
FROM car_showroom
WHERE YEAR(purchase_date) = 2023 
GROUP BY name, city
ORDER BY no_ofsales_2023 DESC
LIMIT 1;

-- 10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?
SELECT name, age, SUM(cost_$) AS revenue2022
FROM car_showroom
WHERE YEAR(purchase_date) = 2022
GROUP BY name, age
ORDER BY revenue2022 DESC
LIMIT 1;






